### ISSUE TITLE
Documento DRS

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-team-desarrollosoftware#4]
[Practica8-FundamentosIngSoftware.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-team-desarrollosoftware/files/13311954/Practica8-FundamentosIngSoftware.pdf)

**Comment by josealfredo79** [comment]
Calificacion...

**Comment by Anamichel-leon** [comment]
30/30 esta conforme a la rubrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
