### ISSUE TITLE
practica 7

### ISSUE THREAD

**Issue by Rufino07** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-team-desarrollosoftware#5]
[practica 8 corregido.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-team-desarrollosoftware/files/13518920/practica.8.corregido.pdf)

**Comment by Eve-lizet** [comment]
28/30

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
